### PR TITLE
Fix running in Docker container

### PR DESCRIPTION
**Pull request by jonashaag**
#46

Based on #45

### CODE REVIEW

**Comment by jonashaag** [comment]
@ Tibormach can you try this (`jonashaag/provision-with-micromamba@docker`)

**Comment by jonashaag** [comment]
@wolfv what's the reason for using `wget` if available (as opposed to always using `curl`)?

**Comment by jonashaag** [comment]
> @wolfv what's the reason for using `wget` if available (as opposed to always using `curl`)?

@wolfv

**Comment by wolfv** [comment]
I guess this needs to be rebased and rebuilt, right? I can take care of that tomorrow

**Comment by wolfv** [comment]
If curl is available on osx and linux we can happily just switch to it.

**Comment by jonashaag** [comment]
@tiberomach did you have the chance to try this branch?

**Pull request closed without merging**
