### PR TITLE
Adding selectors to "extra-specs"

### PR DESCRIPTION
**Pull request by tdegeus**

### CODE REVIEW

**Review by beckermr — CHANGES_REQUESTED** [review]
Please edit the index.js and not the files in dist.

**Comment by tdegeus** [comment]
@wolfv @beckermr In testing I get an error that is I think not 'mine'. Could you help me there?

**Comment by beckermr** [comment]
You need to rebuild the code using the commands in the readme. That may not fix it but try that first.

**Comment by tdegeus** [comment]
Ok, that was not hard to solve
https://stackoverflow.com/a/69699772/2646505

**Comment by beckermr** [comment]
Yeah this is really odd.

**Comment by tdegeus** [comment]
I found it @beckermr , it was set in `action.yml`. So totally good to go from my side, happy to take your review

**Review by beckermr — APPROVED** [review]

**Pull request closed without merging**
