### PR TITLE
Enabling Windows + Bash

### PR DESCRIPTION
**Pull request by tdegeus**

### CODE REVIEW

**Comment by tdegeus** [comment]
@wolfv @beckermr Do you happen to know if `process.shell === 'bash'` is the way to go?

**Comment by beckermr** [comment]
I do not. Windows is a mystery to me.

**Comment by wolfv** [comment]
@tdegeus have a look at #18

**Comment by tdegeus** [comment]
Closing in favour of https://github.com/mamba-org/provision-with-micromamba/pull/18

**Pull request closed without merging**
