### PR TITLE
Allow micromamba install without env

### PR DESCRIPTION
**Pull request by jonashaag**

### CODE REVIEW

**Comment by jonashaag** [comment]
@wolvf

**Comment by jonashaag** [comment]
@wolfv again. Is there a way to activate for me for all future pushes?

**Comment by wolfv** [comment]
@jonashaag for the CI? I think the only way would be to get something of yours merged or you can experiment in your fork and activate github actions to rnu in your branch in the clone.

**Comment by wolfv** [comment]
I think ideally, btw., we'd implement env caching here :) that would be super cool (and teh github actions/cache looks quite easy to use).

**Comment by jonashaag** [comment]
Yes will work on that soon. Do you think allowing install without env has any value anyways? I need it for env caching only, but maybe there are other use cases.

In any case I would like to merge the refactoring

**Comment by wolfv** [comment]
Yes, happy to merge the refactoring. I also don't mind the other changes in here -- I think it might be useful :)

**Pull request closed without merging**
