### PR TITLE
Activating correct on `cmd`

### LINKED ISSUE #39: Not working out of the box with `cmd`
Currently I need to activate the conda environment by hand on the `cmd` shell. Here are my instructions
```yaml
    strategy:
      fail-fast: false
      matrix:
        runs-on: [windows-latest]

    name: ${{ matrix.runs-on }} • x64 ${{ matrix.args }} • py
    runs-on: ${{ matrix.runs-on }}

    steps:

    - name: Basic GitHub action setup
      uses: actions/checkout@v2

    - name: Set conda environment
      uses: mamba-org/provision-with-micromamba@main
      with:
        environment-file: environment.yaml
        environment-name: myenv

    - name: Build and install Python module
      shell: cmd /C CALL {0}
      run: |
        call micromamba activate myenv
        python -m pip install . -vv
```

### PR DESCRIPTION
**Pull request by tdegeus**
Fixes #39

### CODE REVIEW

**Comment by tdegeus** [comment]
What is a bit funny though is that NumPy *does* seem to be found

**Comment by jonashaag** [comment]
Does it make sense to merge this test with some of the existing ones?

**Comment by tdegeus** [comment]
I would have thought that this test is completely unnecessary as I was thinking that https://github.com/mamba-org/provision-with-micromamba/blob/main/.github/workflows/test.yml did the job. Turns out however that something is going wrong

**Comment by jonashaag** [comment]
@tdegeus what's the status of this PR?

**Comment by tdegeus** [comment]
@jonashaag I'm pretty sure this should work, but doesn't. I briefly looked at the Action, but I lacked the time/expertise to come up with a fix.

**Comment by jonashaag** [comment]
OK, looks like the Autorun code isn't executed.

**Comment by jonashaag** [comment]
Actually this is covered by our tests and fails in the tests as well but the failure is ignored.

**Comment by tdegeus** [comment]
Thanks for investigating @jonashaag . So it *is* a bug that needs solving?

**Comment by jonashaag** [comment]
Yes

**Pull request closed without merging**
