### PR TITLE
Readme updates

### PR DESCRIPTION
**Pull request by zmoon**
I wanted to add a note about the #54 upshot to the parameter descriptions. Also tried to make some things easier to read (IMO) in the readme by adding some more Markdown styling.

### CODE REVIEW

**Comment by jonashaag** [comment]
Thanks for the PR. 

I think it is harder to read now. Maybe we can use italics like the Python docs?

**Comment by zmoon** [comment]
That's a good idea. Like italics when referring to parameters that are in the parameter list? That would be the rST style. Do you have a preference between `_` and `*`?

**Comment by jonashaag** [comment]
Yes and no :)

**Comment by jonashaag** [comment]
Yes let's keep `main` but a new PR with the updates is welcome :) Also if you are looking to contribute even more let me know :-D

**Pull request merged**
