### PR TITLE
allow specification of micromamba version, and default to 0.9.2

### PR DESCRIPTION
**Pull request by wolfv**

### CODE REVIEW

**Review by beckermr — CHANGES_REQUESTED** [review]
Is there a way for us to always default to the latest? This would avoid having to bump the version here regularly.

**Comment by wolfv** [comment]
sure, we could just change the default value to `latest`. I am doing this because we're currently having some issues with the config stuff on micromamba and this relieves a bit of the pressure ... I am happy to put it back to latest once we've sorted all that out.

**Comment by beckermr** [comment]
You'll need to retag on master.

**Comment by wolfv** [comment]
thx!

**Pull request merged**
